package hibernatepojos;
// Generated Apr 30, 2022 11:35:21 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userUsername;
     private String userPassword;
     private String userEmail;
     private String userNickname;
     private String userProfilepic;
     private String userType;

    public User() {
    }

	
    public User(String userUsername, String userEmail) {
        this.userUsername = userUsername;
        this.userEmail = userEmail;
    }
    public User(String userUsername, String userPassword, String userEmail, String userNickname, String userProfilepic, String userType) {
       this.userUsername = userUsername;
       this.userPassword = userPassword;
       this.userEmail = userEmail;
       this.userNickname = userNickname;
       this.userProfilepic = userProfilepic;
       this.userType = userType;
    }
   
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserNickname() {
        return this.userNickname;
    }
    
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname;
    }
    public String getUserProfilepic() {
        return this.userProfilepic;
    }
    
    public void setUserProfilepic(String userProfilepic) {
        this.userProfilepic = userProfilepic;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }




}


